#spring.datasource.url=jdbc:postgresql://                         :5432/de2slot6r3tnv
#postgresql://demo_ventas_user:UzGuPAO0fTbHkJZtcjb939WCkLebxfCu@dpg-d71k7ov5r7bs73dv6scg-a.oregon-postgres.render.com/demo_ventas
spring.datasource.url=jdbc:postgresql://dpg-d71k7ov5r7bs73dv6scg-a:5432/demo_ventas
spring.datasource.username=demo_ventas_user
spring.datasource.password=UzGuPAO0fTbHkJZtcjb939WCkLebxfCu
#spring.datasource.driver-class-name=com.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# Thymeleaf
spring.thymeleaf.cache=false
