spring.datasource.url=jdbc:postgresql://c5cqb8h0eop3g3.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/de2slot6r3tnv
spring.datasource.username=ufhtu34buhnp6k
spring.datasource.password=p1e65e58596c6f17b75ce0372a41a79b0402f0b12055a8bbfef33b8135580bc2b

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# Thymeleaf
spring.thymeleaf.cache=false
